version: '3.8'

services:
  photon-neuro:
    build:
      context: .
      dockerfile: Dockerfile.production
      args:
        BUILD_DATE: "${BUILD_DATE:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"
        VERSION: "0.6.0-autonomous"
    image: photon-neuromorphics:0.6.0-autonomous
    container_name: photon-neuro-app
    restart: unless-stopped
    
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - ENV=production
    
    volumes:
      - ./data:/app/data:ro
      - ./logs:/app/logs
    
    networks:
      - photon-network
    
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    
    healthcheck:
      test: ["CMD", "python", "-c", "import photon_neuro; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional monitoring services
  prometheus:
    image: prom/prometheus:latest
    container_name: photon-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - photon-network
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: photon-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=photon-admin
    networks:
      - photon-network
    profiles:
      - monitoring

networks:
  photon-network:
    driver: bridge

volumes:
  grafana-data:
