apiVersion: v1
kind: ConfigMap
metadata:
  name: photon-neuro-config
  namespace: photon-neuro
data:
  LOG_LEVEL: "INFO"
  PYTHONPATH: "/app"
  config.yaml: |
    photon_neuro:
      simulation:
        default_wavelength: 1550e-9
        cache_size: 256
      performance:
        parallel_workers: 4
        enable_caching: true
